version: '3'

services:
    
  mongodb:
    image: mongo
    container_name: mongodb   
    ports:
      - "27017:27017"
    restart: unless-stopped       
    # environment:
      # - MONGO_INITDB_ROOT_USERNAME=admin
      # - MONGO_INITDB_ROOT_PASSWORD=p4ssw0rd
    volumes:
      - /usr/local/mongodb:/todo
      
  mongo-express:
    image: mongo-express
    container_name: mongo-express    
    ports:
      - "8080:8081"
    restart: unless-stopped       
    environment:
      # - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      # - ME_CONFIG_MONGODB_ADMINPASSWORD=p4ssw0rd
      - ME_CONFIG_MONGODB_SERVER=mongodb
      